dashboard:
    path:     /
    defaults: { _controller: LunchBundle:Dashboard:index }

participant_create:
    path:     /participant/create
    defaults: { _controller: LunchBundle:Participant:create }

participant_delete:
    path:     /participant/delete/{id}
    defaults: { _controller: LunchBundle:Participant:delete }

participant_list:
    path:     /participant/list
    defaults: { _controller: LunchBundle:Participant:list }

group_list:
    path:     /group/list
    defaults: { _controller: LunchBundle:Group:list }
