dashboard:
    path:     /
    defaults: { _controller: LunchBundle:Dashboard:index }

send_invites:
    path:     /send-invites
    defaults: { _controller: LunchBundle:Dashboard:sendInvites }

participant_create:
    path:     /participant/create
    defaults: { _controller: LunchBundle:Participant:create }

participant_delete:
    path:     /participant/delete/{id}
    defaults: { _controller: LunchBundle:Participant:delete }

participant_edit:
    path:     /participant/edit/{id}
    defaults: { _controller: LunchBundle:Participant:edit }

participant_confirm:
    path:     /participant/confirm/{id}
    defaults: { _controller: LunchBundle:Participant:confirmParticipation }

participant_list:
    path:     /participant/list
    defaults: { _controller: LunchBundle:Participant:list }

group_list:
    path:     /group/list
    defaults: { _controller: LunchBundle:Group:list }

group_generate:
    path:     /group/generate
    defaults: { _controller: LunchBundle:Group:generate }
