dashboard:
    path:     /
    defaults: { _controller: LunchBundle:Dashboard:index }

participant_create:
    path:     /user/create
    defaults: { _controller: LunchBundle:Participant:create }

participant_delete:
    path:     /user/delete
    defaults: { _controller: LunchBundle:Participant:delete }

participant_list:
    path:     /user/list
    defaults: { _controller: LunchBundle:Participant:list }
